#!/bin/python3
import sys
import os
import optparse

from task.walking_task import WalkingTask
from task.base_task import BaseTask
from task.print_task import PrintTask

COMMA: str = ","
SEMICOLON: str = ";"
SPACE: str = " "

S_print: str = "print"
S_copy: str = "copy"
S_move: str = "move"
S_delete: str = "delete"
S_help: str = "help"
S_comma: str = ","
S_semicolon: str = ";"
S_space: str = " "
S_tab: str = "\t"
S_newline: str = "\n"

def main():
    #Declare supported tasks
    tasks_list: dict = {}
    tasks_list[S_print] = PrintTask(S_print, "Print directory content")
    
    help_string: str = ""
    task: BaseTask = None
    command_name_width: int = 10
    for task in tasks_list.values():
        help_string += f"\n  {task.name}{S_space * (command_name_width - len(task.name))}{task.description}"
    help_string += f"\n  {S_help}{S_space * (command_name_width - len(S_help))}Show help message and exit"
    
    parser: optparse.OptionParser = optparse.OptionParser(usage="%prog command [options] DIRECTORY\n\nCommands:    " + help_string)
    args: list = sys.argv[1:]
    if len(args) <= 0:
        parser.print_help()
        sys.exit(0)
    
    command: str = str(args[0])
    if command == "-h" or command == "--help" or command == "help":
        parser.print_help()
        sys.exit(0)
    if command not in tasks_list:
        print(f"[E] Not supported command:{command}")
        sys.exit(1)
    task = tasks_list[command]
    args = args[1:]
    if not task.parse_args(args):
        sys.exit(1)
    #task.option.debug = True
    task.run()
    if task.status:
        print(f"Success")
    else:
        print("Failed")

main()