#!/bin/python3
import sys
import os
import optparse

from task.walking_task import WalkingTask
from task.print_task import PrintTask

COMMA: str = ","
SEMICOLON: str = ";"
SPACE: str = " "

COMMAND_PRINT: str = "print"
COMMAND_COPY: str = "copy"
COMMAND_MOVE: str = "move"
COMMAND_DELETE: str = "delete"
DEFAULT_COMMAND: str = COMMAND_PRINT

def main():
    parser: optparse.OptionParser = optparse.OptionParser("%prog [options] directory")
    parser.add_option("-v", "--verbose", action="store_false")
    parser.add_option("-q", "--quiet", action="store_false")
    parser.add_option("-r", "--recursive", action="store_false")
    parser.add_option("-j", "--jobs", default=1)
    parser.add_option("-x", "--exclude", default=None)
    parser.add_option("-i", "--include", default="*")
    parser.add_option("-c", "--command", default=None)

    opts, args = parser.parse_args()
    if len(args) <= 0:
        print("No any directory specified")
        parser.print_usage()
        sys.exit(1)
    specified_directory: str = args[0]
    if not os.path.isdir(specified_directory):
        if not os.path.isdir(os.path.abspath(specified_directory)):
            print(f"Error:{specified_directory} is not a valid directory")
            sys.exit(1)
    specified_directory = os.path.abspath(specified_directory)
    parsing_task: WalkingTask = WalkingTask("Parsing")
    parsing_task.option.verbose = True if opts.verbose is not None else False
    parsing_task.option.quiet = True if opts.quiet is not None else False
    parsing_task.option.recursive = True if opts.recursive is not None else False
    parsing_task.option.jobs = int(opts.jobs) if str(opts.jobs).isnumeric() else 1
    if opts.exclude is not None:
        string_list: list = None
        sub_string: str = ""
        sub_list: list = None
        pattern: str = ""
        string_list = opts.exclude.split(COMMA)
        for sub_string in string_list:
            sub_list = sub_string.strip().split(SEMICOLON)
            for pattern in sub_list:
                parsing_task.option.excluded_patterns.append(pattern.strip())
    if opts.include is not None:
        string_list: list = None
        sub_string: str = ""
        sub_list: list = None
        pattern: str = ""
        string_list = opts.include.split(COMMA)
        for sub_string in string_list:
            sub_list = sub_string.strip().split(SEMICOLON)
            for pattern in sub_list:
                parsing_task.option.included_patterns.append(pattern.strip())

    parsing_task.option.debug = False
    #print(parsing_task.option)
    parsing_task.run([specified_directory])
    if not parsing_task.status:
        sys.exit(1)
    
    command: str = opts.command
    if command is None:
        command = DEFAULT_COMMAND
    
    if command == COMMAND_PRINT:
        print_task: PrintTask = PrintTask("Printing")
        print_task.option.verbose = True if opts.verbose is not None else False
        print_task.option.quiet = True if opts.quiet is not None else False
        print_task.option.debug = True
        print_task.run([parsing_task.directory])
        if not print_task.status:
            sys.exit(1)
main()